# Setup
title: Marc Johansen
tagline: 
url: https://marcjohansen.net
paginate: 
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Accessing pages _pages and additional includes
include:
  - .htaccess
  - _pages
  - files

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Collections [ADDED]
collections:
  teaching:
    output: false
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/


sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-7HZ85B3595

# Specify the author for blog posts
author:
  name: Marc Johansen
  url: https://marcjohansen.net
  email: marcjohansen@creighton.edu

# Custom vars
#version: 3.0.0fr
version: 4.0
